import assert from 'node:assert/strict';
import http from 'node:http';
const origin = process.env.DEMO_ORIGIN || 'http://127.0.0.1:8000';
const request = (path, options = {}) => fetch(origin + path, {signal: AbortSignal.timeout(15000), ...options});
const headers = {Origin: origin, 'Content-Type': 'application/json'};
assert.equal((await request('/api/config')).status, 200);
const foreignHostStatus = await new Promise((resolve, reject) => {
  const req = http.get(origin + '/api/config', {headers: {Host: 'attacker.invalid'}}, response => { response.resume(); resolve(response.statusCode); });
  req.on('error', reject);
});
assert.equal(foreignHostStatus, 403);
assert.equal((await request('/api/ping', {method: 'POST', body: '{}'})).status, 403);
assert.equal((await request('/api/ping', {method: 'POST', headers: {...headers, Origin: 'https://attacker.invalid'}, body: '{}'})).status, 403);
assert.equal((await request('/api/ping', {method: 'POST', headers: {Origin: origin}, body: '{}'})).status, 415);
assert.equal((await request('/api/ping', {method: 'POST', headers, body: 'x'.repeat(1025)})).status, 413);
assert.equal((await request('/api/ping', {method: 'POST', headers, body: '{"relays":["http://127.0.0.1"]}'})).status, 400);
assert.equal((await request('/api/game', {method: 'POST', body: '{}'})).status, 403);
assert.equal((await request('/api/game', {method: 'POST', headers: {...headers, Origin: 'https://attacker.invalid'}, body: '{}'})).status, 403);
assert.equal((await request('/api/game', {method: 'POST', headers, body: '{"lobby":"attacker"}'})).status, 400);
assert.equal((await request('/api/unknown')).status, 403);
assert.equal((await request('/%2e%2e%2fbuild.gradle')).status, 404);
const first = await request('/api/ping', {method: 'POST', headers, body: '{}'});
assert.equal(first.status, 201);
assert.equal(first.headers.get('cache-control'), 'no-store');
const a = await first.json();
assert.match(a.token, /^[0-9a-f]{64}$/);
assert.match(a.roomKeySeed, /^[0-9a-f]{64}$/);
assert.notEqual(a.token, a.roomKeySeed);
assert.equal((await request('/api/ping', {method: 'POST', headers, body: '{}'})).status, 429);
assert.equal((await request('/api/ping/' + a.token, {method: 'DELETE', headers})).status, 200);
await new Promise(resolve => setTimeout(resolve, 8200));
const second = await request('/api/ping', {method: 'POST', headers, body: '{"mode":"turn"}'});
assert.equal(second.status, 201);
const b = await second.json();
assert.notEqual(a.roomKeySeed, b.roomKeySeed);
assert.notEqual(a.receiverPubkey, b.receiverPubkey);
assert.notEqual(a.token, b.token);
assert.equal((await request('/api/ping/' + b.token, {method: 'DELETE', headers})).status, 200);
const practice = await request('/api/game', {method: 'POST', headers, body: '{"mode":"private"}'});
assert.equal(practice.status, 201);
const game = await practice.json();
assert.match(game.token, /^[a-f0-9]{64}$/);
assert.match(game.roomKeySeed, /^[a-f0-9]{64}$/);
assert.equal(game.botPubkeys.length, 2);
for (const pubkey of game.botPubkeys) assert.match(pubkey, /^[a-f0-9]{64}$/);
assert.notEqual(game.botPubkeys[0], game.botPubkeys[1]);
assert.deepEqual(game.relays, ['wss://relay.ngengine.org', 'wss://relay2.ngengine.org', 'wss://nostr.rblb.it']);
assert.match(game.turnUri, /^wss:\/\//);
assert.notEqual(game.token, game.roomKeySeed);
assert.equal((await request('/api/config').then(r => r.json())).privateGameRooms, 1);
assert.equal((await request('/api/game/' + game.token, {method: 'POST', headers, body: '{}'})).status, 200);
assert.equal((await request('/api/game', {method: 'POST', headers, body: '{"mode":"private"}'})).status, 429);
assert.equal((await request('/api/game/' + game.token, {method: 'DELETE', headers})).status, 200);
assert.equal((await request('/api/config').then(r => r.json())).privateGameRooms, 0);
const harbor = await request('/api/game', {method: 'POST', headers, body: '{"mode":"shared"}'});
assert.equal(harbor.status, 200);
const shared = await harbor.json();
assert.equal(shared.roomKeySeed, 'sats-seas-lobby');
assert.deepEqual(shared.relays, game.relays);
assert.equal(shared.turnUri, game.turnUri);
console.log('PASS backend: Host/Origin checks, bounded ping and practice rooms, random isolation, rate limits, heartbeat and cleanup.');
